export const labels = {
    'reference': 'Reference',
    'typeReference': 'Type Reference',
    'folio': 'Folio',
    'journalType': 'Journal Type',
    'date': 'Date',
    'search': 'Search',
    'journalCanceled': 'Journal Canceled',
    'errorOccured': 'Error Occured !',
    'ledgerNumber': 'Ledger No.',
    'ledgerName': 'Name',
    'ledgerDesc': 'Description',
    'currency': 'Currency',
    'd/c': 'D/C',
    'amount': 'Amount',
    'valueDate': 'Value Date',
    'description1': 'Desc 1',
    'from': 'From',
    'to': 'To',
    'ledgers': 'Ledgers',
    'balance': 'Balance',
    'journal': 'Journal',
    'clear': 'Clear Page',
    'pending': 'Pending',
    'copyJv': 'Copy JV',
    'cancel': 'Cancel',
    'save' : 'Save',
    'project': 'Project',
    'costCenter': 'Cost Center',
    'type' :'Type',
    'manualNumber' : 'Manual No.',
    'remark' : 'Remark',
    'projects': 'Projects',
    'percentage' : 'Perc. %',
    'checks' : 'Checks',
    'division1' : 'Division 1',
    'division2' : 'Division 2',
    'checkNo' : 'Check No.',
    'bank' : 'Bank',
    'billNo' : 'Bill No.',
    'lockedPeriod' : 'Locked Period',
    'bills' : 'Bills',
    'lock' : 'Lock',
    'unlock' : 'UnLock',
    'sales-jv' : 'Sales JV',
    'purchaseJvOrderUnConfirmed' : 'Order unconfirmed',
    'purchaseJvOrderConfirmed' : 'Order confirmed',
    'next' : 'التالي',

};
